# Generated by Django 4.1.7 on 2023-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_alter_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='approved',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('no_approval', 'Needs No Approval')], default='pending', max_length=20),
        ),
    ]
