# Generated by Django 4.1.7 on 2023-06-04 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_document_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentAccess',
            new_name='Permission',
        ),
    ]
