# Generated by Django 4.1.7 on 2023-06-04 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_rename_documentaccess_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('document', 'user', 'access')},
        ),
    ]
