# Generated by Django 4.1.7 on 2023-06-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_permission_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.rank'),
        ),
    ]
