# Generated by Django 4.1.7 on 2023-06-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_profile_staff_id_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff_id',
            field=models.IntegerField(unique=True),
        ),
    ]
