# Generated by Django 4.1.7 on 2023-06-20 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_alter_profile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='allowed_access',
        ),
        migrations.AddField(
            model_name='document',
            name='read_access',
            field=models.ManyToManyField(blank=True, related_name='can_read_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='update_access',
            field=models.ManyToManyField(blank=True, related_name='can_update_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
