# Generated by Django 4.1.7 on 2023-06-20 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_remove_document_allowed_access_document_read_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='read_access',
            field=models.ManyToManyField(blank=True, related_name='access_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='update_access',
            field=models.ManyToManyField(blank=True, related_name='update_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
