# Generated by Django 4.1.7 on 2023-07-28 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.document'),
        ),
    ]
