# Generated by Django 4.1.7 on 2023-08-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_notification_receivers_notification_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='api.position'),
        ),
    ]
