# Generated by Django 4.1.7 on 2023-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='position_access',
            field=models.ManyToManyField(blank=True, related_name='position_documents', to='api.position'),
        ),
    ]
