# Generated by Django 4.1.7 on 2023-08-24 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_alter_document_position_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('receiver', 'message', 'document')},
        ),
    ]
