# Generated by Django 4.1.7 on 2023-08-24 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_alter_notification_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('receiver', 'message', 'document')},
        ),
    ]
