# Generated by Django 4.1.7 on 2023-08-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_notification_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='file',
        ),
        migrations.AddField(
            model_name='version',
            name='changes',
            field=models.TextField(default='h'),
            preserve_default=False,
        ),
    ]
