# Generated by Django 4.1.7 on 2023-08-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_version_changed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='changes',
            new_name='rationale',
        ),
    ]
