# Generated by Django 4.1.7 on 2023-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_changes_auditlog_rationale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('word', 'Word'), ('excel', 'Excel'), ('pdf', 'PDF'), ('powerpoint', 'PowerPoint'), ('csv', 'CSV')], max_length=255),
        ),
    ]
